---
abstract: "fallback keyring for environments\nwhere no better keyring is available."
author:
  - 'Marcin Kasperski <Marcin.Kasperski@mekk.waw.pl>'
build_requires:
  Pod::Readme: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
keywords:
  - keyring
  - passwords
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Passwd-Keyring-Memory
provides:
  Passwd::Keyring::Memory:
    file: lib/Passwd/Keyring/Memory.pm
    version: 0.2404
requires:
  perl: 5.006
resources:
  bugtracker: https://bitbucket.org/Mekk/perl-keyring-memory/issues
  homepage: http://bitbucket.org/Mekk/perl-keyring-memory
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/Mekk/perl-keyring-memory
version: 0.2404
