---
abstract: "fallback keyring for environments\nwhere no better keyring is available."
author:
  - 'Marcin Kasperski <Marcin.Kasperski@mekk.waw.pl>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Passwd-Keyring-Memory
provides:
  Passwd::Keyring::Memory:
    file: lib/Passwd/Keyring/Memory.pm
    version: 0.21
requires:
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.21
